package com.semernik.rockfest.type;

import com.semernik.rockfest.container.ErrorMessagesContainer;

public enum ErrorMessage {

	ERROR_MESSAGE,
	REGISTRATION_FAILURE,
	INVALID_EMAIL,
	INVALID_NEW_LOGIN,
	INVALID_NEW_PASSWORD,
	LOGIN_FAILURE,
	RATING_FAILURE,
	GENRE_ERROR,
	SINGER_ERROR,
	COMPOSITIONS_ERROR,
	COMPOSITION_ERROR,
	LINK_ERROR,
	SAVE_GENRE_ERROR,
	SAVE_SINGER_ERROR,
	SAVE_COMPOSITION_ERROR,
	UPDATE_TITLE_ERROR,
	UPDATE_DESCRIPTION_ERROR,
	COMPOSITION_GENRES_ERROR,
	UPDATE_COMPOSITION_GENRES_ERROR,
	COMMENTS_FAILURE,
	SAVE_LINK_ERROR,
	SAVE_COMMENT_ERROR,
	DELETE_COMMENT_ERROR,
	UPDATE_YEAR_ERROR,
	DELETE_LINK_ERROR,
	ADD_LINK_ERROR,
	USER_RATING_ERROR,
	SEARCH_ERROR,
	USER_INFO_CHANGE_FAILURE,
	OCCUPIED_LOGIN,
	USER_PROFILE_ERROR,
	BAN_DATE_SAVING_FAILURE,
	ADMIN_PROFILE_ERROR,

	INVALID_PARAMETERS,
	INVALID_LOGIN_PARAMETERS,
	INVALID_PASSWORD,
	INVALID_GENRE,
	INVALID_SINGER,
	INVALID_COMPOSITION,
	INVALID_ID,
	INVALID_COMMENT,
	INVALID_LINK,
	INVALID_SEARCH_PATTERN,
	INVALID_NEW_DESCRIPTION,
	INVALID_NEW_TITlE,
	INVALID_NEW_YEAR,
	INVALID_COMPOSITION_GENRES,
	INVALID_COMMENT_DELETION,
	INVALID_LINK_DELETION,
	INVALID_USER_RATING,
	INVALID_LOCALE,
	INVALID_REGISTRATION_PARAMETERS,
	INVALID_USER,
	INVALID_ADMIN,
	INVALID_LOGIN,
	INVALID_DATE
	;

	public String findMessage(){
		String message = ErrorMessagesContainer.findMessage(this.toString());
		return message;
	}

	@Override
	public String toString(){
		return this.name().toLowerCase();
	}

}
